/* 3. STORED PROCEDURE */

/* DML STATEMENTS */

DROP PROCEDURE IF EXISTS UML_DML_Statements;

DELIMITER $$

CREATE PROCEDURE UML_DML_Statements()
BEGIN

/* DML STATEMENTS */

/*3.1 ADMINISTRATOR */

INSERT INTO ADMINISTRATOR (FIRST_NAME, LAST_NAME, CONTACT) VALUES ('Ryan', 'Gosling', '+49 15511234567');
INSERT INTO ADMINISTRATOR (FIRST_NAME, LAST_NAME, CONTACT) VALUES ('Patrick', 'Bateman', '+49 15512345671');
INSERT INTO ADMINISTRATOR (FIRST_NAME, LAST_NAME, CONTACT) VALUES ('Lou', 'Bloom', '+49 15513456712');

/* 3.2 DEPARTMENT */

INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, DEAN_ID) VALUES (1,'Computer Science', NULL);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, DEAN_ID) VALUES (2,'Mathematics', NULL);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, DEAN_ID) VALUES (3,'Business', NULL);
INSERT INTO DEPARTMENT (DEPT_ID, DEPT_NAME, DEAN_ID) VALUES (4,'Building Physics', NULL);

/* 3.3 COURSE */

/* Computer Science */
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (11, 1, NULL, 'Bachelor of Computer Science', 'bcs', 210, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (12, 1, NULL, 'Bachelor of Augmented Reality', 'bar', 210, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (13, 1, NULL, "Bachelor's degree in digitalization and information management", 'bdi', 210, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (14, 1, NULL, 'Bachelor Surveying and Geoinformatics', 'bsg', 210, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (15, 1, NULL, 'Master Photogrammetry and Geoinformatics', 'mpg', 90, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (16, 1, NULL, 'Master Software Technology', 'mst', 90, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (17, 1, NULL, 'Master Digital Processes and Technologies', 'mdp', 90, NULL, NULL);

/* Mathematics */
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (21, 2, NULL, 'Bachelor Applied Mathematics and AI', 'bam', 210, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (22, 2, NULL, 'Master Mathematics', 'mam', 90, NULL, NULL);

/* Business */
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (31, 3, NULL, 'Bachelor of Business Administration', 'bba', 210, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (32, 3, NULL, 'Business Administration International Business course', 'bai', 210, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (33, 3, NULL, 'Bachelor of Infrastructure Management', 'bim', 210, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (34, 3, NULL, 'Bachelor of Business Informatics', 'bbi', 210, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (35, 3, NULL, 'Master General Management', 'mgm', 90, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (36, 3, NULL, 'Master Environmentally Oriented Logistics', 'meo', 90, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (37, 3, NULL, "Master of Business Psychology", 'mdb', 90, NULL, NULL);

/* Building Physics */
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (41, 4, NULL, 'Bachelor of Building Physics', 'bbp', 210, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (42, 4, NULL, 'Bachelor of Climate Engineering', 'bce', 210, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (43, 4, NULL, 'Master Building Physics', 'mbp', 90, NULL, NULL);
INSERT INTO COURSE (COURSE_ID, DEPT_ID, INSTRUCTOR_ID, COURSE_NAME, COURSE_CODE, CREDITS, BUILDING_NO, ROOM_NO) VALUES (44, 4, NULL, 'Master in Sustainable Energy Competence', 'mse', 90, NULL, NULL);

END;

$$

DELIMITER ;
